### ISSUE TITLE
Adds "/opt/tools/ads-catcher//blacklist//youtube-blacklist.txt" to blacklist on Pi-hole

### ISSUE THREAD

**Issue by ghost** [pebdev/pihole#1]
I noticed that instead of entering the blacklisted domains into Pi-hole's blacklist, it instead added "/opt/tools/ads-catcher//blacklist//youtube-blacklist.txt" as an entry for 'Exact blocking'. Inside the youtube-blacklist.txt file itself are googlevideo.com entries, but I thought these needed to be added instead of the path to a txt file?

![youtube-blacklist](https://user-images.githubusercontent.com/46271764/55151276-fa27af00-51a1-11e9-9991-7cf1d0fe31ba.jpg)

**Comment by pebdev** [comment]
Thanks for your feedback.

I did it to avoid to have a big list of blocked addresses in the pi-hole interface (after one week I have 60 addresses in this file). In fact I based my choice on other blacklist files provided by default with pi-hole. This solution improves readability but user can't remove an address (in the HMI), I'm agree with you, it's not the best solution.

I will update tool by adding a configuration file to allow user to choose.

**Comment by ghost** [comment]
Thanks for this, because for some reason having the txt file listed there didn’t actually block any of the domains inside, I’m not sure why.

**Comment by pebdev** [comment]
Fixed with new release v1.1.0
