### ISSUE TITLE
Provide option to Restart DNS Resolver instead of Running Gravity

### ISSUE THREAD

**Issue by ghost** [pebdev/pihole#3]
Correct me if I am wrong, but it seems that at the moment, you are running gravity every 10 minutes, meaning lists are downloaded very often. If so, this is something I would not be comfortable with as servers usually blacklist IPs or so when Pi-hole is updated too often (default is Sunday weekly, I've seen at most daily options).

Would it be possible to instead just restart the DNS resolver so the blacklist entries are taken into effect without having to update entirely? Command for this is: `sudo killall -SIGHUP pihole-FTL`

**Comment by pebdev** [comment]
Yes, you are right, today it works but it's not a clean solution.
I saw an option in the pi-hole documentation : pihole -b <blacklist_address>
I did some tests, there are only local actions, so it's perfect.
I'll fix that for the next release.

**Comment by pebdev** [comment]
Fixed with the new release v1.2.0
